language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

matrix:
  include:
    - python: '3.7'  # temp solution until python 3.7 is more cleanly supported
      dist: xenial
      sudo: true

install:
  - pip install .
  - pip install -r requirements-extras.txt
  - pip install -r requirements-dev.txt
  - pip list
  - pip show urbansim_templates

script:
  - cd tests
  - coverage run --source urbansim_templates --module pytest --verbose

after_success:
  - coverage report --show-missing
  - coveralls